<?php

namespace Proxies\__CG__\Couture\GestionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \Couture\GestionBundle\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'nom', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'prenom', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'telephone', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'nombreCommande', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'nombreAchat', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'typeClient', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'identifiant', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'sexe', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'adresse', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'mesure'];
        }

        return ['__isInitialized__', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'nom', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'prenom', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'telephone', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'email', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'nombreCommande', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'nombreAchat', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'typeClient', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'identifiant', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'sexe', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'adresse', '' . "\0" . 'Couture\\GestionBundle\\Entity\\Client' . "\0" . 'mesure'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreCommande($nombreCommande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreCommande', [$nombreCommande]);

        return parent::setNombreCommande($nombreCommande);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreCommande()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreCommande', []);

        return parent::getNombreCommande();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreAchat($nombreAchat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreAchat', [$nombreAchat]);

        return parent::setNombreAchat($nombreAchat);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreAchat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreAchat', []);

        return parent::getNombreAchat();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeClient($typeClient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeClient', [$typeClient]);

        return parent::setTypeClient($typeClient);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeClient', []);

        return parent::getTypeClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdentifiant($identifiant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdentifiant', [$identifiant]);

        return parent::setIdentifiant($identifiant);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdentifiant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdentifiant', []);

        return parent::getIdentifiant();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function getUniqueName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUniqueName', []);

        return parent::getUniqueName();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setMesure(\Couture\GestionBundle\Entity\Mesure $mesure = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMesure', [$mesure]);

        return parent::setMesure($mesure);
    }

    /**
     * {@inheritDoc}
     */
    public function getMesure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMesure', []);

        return parent::getMesure();
    }

}
