<?php

namespace Couture\GestionBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
	public function findLikeName($q)
  	{
    	$query = $this->getEntityManager()
	        ->createQuery('
	            SELECT i FROM CoutureGestionBundle:Client i 
	            WHERE i.prenom LIKE :reference or i.nom LIKE :reference'
	        )->setParameter('reference', $q);
        try
        {
        	return $query->getResult();
        }
        catch (\Doctrine\ORM\NoResultException $e) {
        	return null;
      	}
	}
}
