<?php

namespace Couture\GestionBundle\Repository;

/**
 * CommandeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeProduitRepository extends \Doctrine\ORM\EntityRepository
{
	public function findNetPaie($commande)
  	{
    	$query = $this->getEntityManager()
	        ->createQuery('
	            SELECT sum(i.montantTotal) FROM CoutureGestionBundle:CommandeProduit i 
	            WHERE i.reference = :reference
	            Group BY i.reference'
	        )->setParameter('reference', $commande);
        try
        {
        	return $query->getSingleScalarResult();
        }
        catch (\Doctrine\ORM\NoResultException $e) {
        	return null;
      	}
	}
}
