<?php

namespace Proxies\__CG__\Administration\PharmacieBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pharmacien extends \Administration\PharmacieBundle\Entity\Pharmacien implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'id', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'matricule', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'nom', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'premierPrenom', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'deuxiemePrenom', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'section', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'dateNaissance', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'adresse', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'lieuNaissance', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'telephoneMobile', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'telephoneProfessionnel', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'emailPersonnel', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'emailProfessionnel', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'pharmacie', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'photo', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'dateMetier', 'dateCreation', 'dateModification', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'username', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'apiKey', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'password'];
        }

        return ['__isInitialized__', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'id', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'matricule', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'nom', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'premierPrenom', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'deuxiemePrenom', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'section', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'dateNaissance', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'adresse', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'lieuNaissance', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'telephoneMobile', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'telephoneProfessionnel', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'emailPersonnel', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'emailProfessionnel', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'pharmacie', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'photo', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'dateMetier', 'dateCreation', 'dateModification', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'username', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'apiKey', '' . "\0" . 'Administration\\PharmacieBundle\\Entity\\Pharmacien' . "\0" . 'password'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pharmacien $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricule($matricule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricule', [$matricule]);

        return parent::setMatricule($matricule);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricule', []);

        return parent::getMatricule();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPremierPrenom($premierPrenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPremierPrenom', [$premierPrenom]);

        return parent::setPremierPrenom($premierPrenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPremierPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPremierPrenom', []);

        return parent::getPremierPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeuxiemePrenom($deuxiemePrenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeuxiemePrenom', [$deuxiemePrenom]);

        return parent::setDeuxiemePrenom($deuxiemePrenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeuxiemePrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeuxiemePrenom', []);

        return parent::getDeuxiemePrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setSection($section)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSection', [$section]);

        return parent::setSection($section);
    }

    /**
     * {@inheritDoc}
     */
    public function getSection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSection', []);

        return parent::getSection();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateNaissance($dateNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateNaissance', [$dateNaissance]);

        return parent::setDateNaissance($dateNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateNaissance', []);

        return parent::getDateNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuNaissance($lieuNaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuNaissance', [$lieuNaissance]);

        return parent::setLieuNaissance($lieuNaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuNaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuNaissance', []);

        return parent::getLieuNaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneMobile($telephoneMobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneMobile', [$telephoneMobile]);

        return parent::setTelephoneMobile($telephoneMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneMobile', []);

        return parent::getTelephoneMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneProfessionnel($telephoneProfessionnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneProfessionnel', [$telephoneProfessionnel]);

        return parent::setTelephoneProfessionnel($telephoneProfessionnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneProfessionnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneProfessionnel', []);

        return parent::getTelephoneProfessionnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateMetier($dateMetier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateMetier', [$dateMetier]);

        return parent::setDateMetier($dateMetier);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateMetier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateMetier', []);

        return parent::getDateMetier();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailPersonnel($emailPersonnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailPersonnel', [$emailPersonnel]);

        return parent::setEmailPersonnel($emailPersonnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailPersonnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailPersonnel', []);

        return parent::getEmailPersonnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailProfessionel($emailProfessionel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailProfessionel', [$emailProfessionel]);

        return parent::setEmailProfessionel($emailProfessionel);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailProfessionel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailProfessionel', []);

        return parent::getEmailProfessionel();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailProfessionnel($emailProfessionnel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailProfessionnel', [$emailProfessionnel]);

        return parent::setEmailProfessionnel($emailProfessionnel);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailProfessionnel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailProfessionnel', []);

        return parent::getEmailProfessionnel();
    }

    /**
     * {@inheritDoc}
     */
    public function setPharmacie(\Administration\PharmacieBundle\Entity\Pharmacie $pharmacie = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPharmacie', [$pharmacie]);

        return parent::setPharmacie($pharmacie);
    }

    /**
     * {@inheritDoc}
     */
    public function getPharmacie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPharmacie', []);

        return parent::getPharmacie();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreation(\DateTime $dateCreation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreation', [$dateCreation]);

        return parent::setDateCreation($dateCreation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreation', []);

        return parent::getDateCreation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateModification(\DateTime $dateModification = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateModification', [$dateModification]);

        return parent::setDateModification($dateModification);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateModification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateModification', []);

        return parent::getDateModification();
    }

    /**
     * {@inheritDoc}
     */
    public function prePersist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prePersist', []);

        return parent::prePersist();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpdate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpdate', []);

        return parent::preUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setApiKey($apiKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApiKey', [$apiKey]);

        return parent::setApiKey($apiKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getApiKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiKey', []);

        return parent::getApiKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

}
